-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Operator CASCADE;
DROP TABLE IF EXISTS Task_list CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Task_category CASCADE;
DROP TABLE IF EXISTS Priority CASCADE;